#
# Copyright (c) 2020-2025, Arm Limited and affiliates.
# Part of the Arm Toolchain project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

ifndef BIN_PATH
    BIN_PATH=../../../bin
endif

ifndef LIBC
    LIBC=picolibc
endif

MICROBIT_TARGET=--target=armv6m-none-eabi -march=armv6m -mfpu=none -mfloat-abi=soft
AARCH64_TARGET=--target=aarch64-none-elf

MICROBIT_OPTIONS=$(MICROBIT_TARGET) --config=Osize.cfg

CRT_SEMIHOST=-nostartfiles -lcrt0-semihost -lsemihost

CPP_FLAGS=-fno-exceptions -fno-rtti

ifneq ($(wildcard $(BIN_PATH)/$(LIBC).cfg),)
    CFG_FILE=--config=$(LIBC).cfg
else
    CFG_FILE=
endif

ifeq ($(LIBC),picolibc)
    MATH_LIB=
    LIBC_LD_FILE=picolibcpp.ld
else ifeq ($(LIBC),llvmlibc)
    MATH_LIB=-lm
    LIBC_LD_FILE=llvmlibc.ld
else
    $(error Unsupported LIBC=$(LIBC))
endif

QEMU_SEMIHOSTING=-nographic \
-chardev stdio,mux=on,id=stdio0 \
-semihosting-config enable=on,chardev=stdio0 \
-monitor none -serial none
